#!/bin/sh

# prevents i3 from wrapping when cycling through workspaces
case $1 in
    prev) wmctrl -d | sort -k 8 | head -1 | grep '\*' || i3-msg workspace prev;;
    next) wmctrl -d | sort -k 8 | tail -1 | grep '\*' || i3-msg workspace next;;
esac
